log = "stderr"
docker = "http://192.168.56.101:2375"

[backends]
    [backends.redis]
    proto = "tcp"
    listen_ip = "127.0.0.1"
    listen_port = 6379
    ip = "127.0.0.1"
    port = 6378
    max_concurrent = 100

    [backends.redisd]
    proto = "tcp"
    listen_ip = "127.0.0.1"
    listen_port = 6370
    ip = "192.168.56.101"
    port = 8989
    max_concurrent = 100
    container = "redisd"
