log = "stderr"
dns = "172.17.42.1:53"

[backends]

    [backends.redis]
    proto = "tcp"
    ip = "192.168.56.9"
    port = 6379
    query = "redis.dev.docker."
    max_concurrent = 20
    resolver = "srv"

    [backends.production]
    proto = "http"
    ip = "0.0.0.0"
    port = 80
    max_concurrent = 100

[domains]

    [domains.rethinkdb]
    domain = "localhost"
    query = "172.17.0.7:8080"
    resolver = "ip"
