log = "stderr"

[backends]
    [backends.redis]
    proto = "tcp"
    listen_ip = "127.0.0.1"
    listen_port = 6379
    ip = "127.0.0.1"
    port = 6378
    max_concurrent = 100
    cert = "/Users/michael/certs/server-cert.pem"
    key = "/Users/michael/certs/server-key.pem"
